services:

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: zoo_php
    volumes:
      - ./backend:/var/www
      - vendor_data_php:/var/www/vendor
    working_dir: /var/www

  nginx:
    image: nginx:alpine
    container_name: zoo_nginx
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  ui:
    build:
      context: ./docker/ui
      dockerfile: Dockerfile
    container_name: zoo_ui
    working_dir: /app
    volumes:
      - ./frontend:/app
      - node_modules_ui:/app/node_modules
    ports:
      - "5173:5173"

volumes:
  vendor_data_php:
  node_modules_ui: